import './globals.css';
import type { Metadata } from 'next';
import { Inter, Montserrat, Roboto } from 'next/font/google';
import Providers from '../components/Providers';
import AppShell from '../components/Layout/AppShell';

const inter = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
});

export const metadata: Metadata = {
  title: 'CMS Project Admin Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
